spring.application.name=recruiting-system

# MongoDB connection (adjust as needed)
spring.data.mongodb.uri=mongodb+srv://ajayyadavbipul2003_db_user:Ajay1224@cluster0.thj9gnx.mongodb.net/?appName=Cluster0

server.port=${PORT:8080}

# Multipart file upload configuration
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB
spring.servlet.multipart.enabled=true

# Thymeleaf configuration
spring.thymeleaf.cache=false
spring.thymeleaf.enabled=true
spring.thymeleaf.mode=HTML
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html
spring.thymeleaf.check-template=true
spring.thymeleaf.check-template-location=true
